name: Shellcheck Shell Script Check
decription: Run shellcheck shell script checker
inputs:
  files-changed-patterns:
    description: File patterns to determine if test needs to run
    required: false
    type: string
    default: |
      scripts/*.sh
      dev-scripts/*.sh
  trigger-event-name:
    description: "Optional upstream event name"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    # Step 1: Determine whether to run checks (changes or dispatch trigger)
    - name: Checks needed if relevant files change or dispatch trigger
      id: check-skip
      uses: ./.github/actions/determine-run-steps
      with:
        files-changed-patterns: ${{ inputs.files-changed-patterns }}
        trigger-event-name: ${{ inputs.trigger-event-name || github.event_name }}
    # Step 2: Detect version desired, to match that used for pre-commit
    - name: Get Shellcheck version from pyproject.toml
      id: tool-version
      if: steps.check-skip.outputs.run-steps == 'true'
      uses: ./.github/actions/extract-tool-version
      with:
        tool-name: shellcheck
    # Step 3: Run shellcheck action
    - name: Run ShellCheck
      if: steps.check-skip.outputs.run_steps == 'true'
      uses: ludeeus/action-shellcheck@master
      with:
        version: ${{ steps.tool-version.outputs.version }}
