name: Prettier Format Check
decription: Run Prettier format checks (md, json)
# Note: ruff will check pyproject.toml and toml support is immature in
#       prettier so you do not have to include toml files here
inputs:
  prettier_options:
    description: Options for Prettier
    required: false
    default: "--check **/*.{md,json} --ignore-path .prettierignore"
  only_changed:
    description: Run only on changed files
    required: false
    default: false
  files-changed-patterns:
    description: File patterns to determine if test needs to run
    required: false
    type: string
    default: |
      **/*.md
      **/*.json
  trigger-event-name:
    description: "Optional upstream event name"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    # Step 1: Determine whether to run checks (changes or dispatch trigger)
    - name: Checks needed if relevant files change or dispatch trigger
      id: check-skip
      uses: ./.github/actions/determine-run-steps
      with:
        files-changed-patterns: ${{ inputs.files-changed-patterns }}
        trigger-event-name: ${{ inputs.trigger-event-name || github.event_name }}
    # Step 2: Detect tool version desired, to match that used for pre-commit
    - name: Get Prettier version from pyproject.toml
      id: tool-version
      if: steps.check-skip.outputs.run-steps == 'true'
      uses: ./.github/actions/extract-tool-version
      with:
        tool-name: prettier
    # Step 3: Run prettier check
    - name: "Prettier formatting check"
      if: steps.check-skip.outputs.run-steps == 'true'
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: ${{ inputs.prettier_options }}
        only_changed: ${{ inputs.only_changed }}
        prettier_version: ${{ steps.tool-version.outputs.version }}
